import tkinter as tk

root = tk.Tk()
b1 = tk.Button(root, text="arrow", cursor="arrow")
b2 = tk.Button(root, text="circle", cursor="circle")
b3 = tk.Button(root, text="clock", cursor="clock")
b4 = tk.Button(root, text="cross", cursor="cross")
b5 = tk.Button(root, text="dotbox", cursor="dotbox")
b6 = tk.Button(root, text="exchange", cursor="exchange")
b7 = tk.Button(root, text="fleur", cursor="fleur")
b8 = tk.Button(root, text="heart", cursor="heart")
b9 = tk.Button(root, text="man", cursor="man")
b10 = tk.Button(root, text="mouse", cursor="mouse")
b11 = tk.Button(root, text="pirate", cursor="pirate")
b12 = tk.Button(root, text="plus", cursor="plus")
b13 = tk.Button(root, text="question_arrow", cursor="question_arrow")
b14 = tk.Button(root, text="shuttle", cursor="shuttle")
b15 = tk.Button(root, text="sizing", cursor="sizing")
b16 = tk.Button(root, text="spider", cursor="spider")
b17 = tk.Button(root, text="spraycan", cursor="spraycan")
b18 = tk.Button(root, text="star", cursor="star")
b19 = tk.Button(root, text="target", cursor="target")
b20 = tk.Button(root, text="tcross", cursor="tcross")
b21 = tk.Button(root, text="umbrella", cursor="umbrella")
b22 = tk.Button(root, text="watch", cursor="watch")
b23 = tk.Button(root, text="bottom_side", cursor="bottom_side")
b24 = tk.Button(root, text="bottom_left_corner", cursor="bottom_left_corner")
b25 = tk.Button(root, text="bottom_right_corner", cursor="bottom_right_corner")
b26 = tk.Button(root, text="left_side", cursor="left_side")
b27 = tk.Button(root, text="right_side", cursor="right_side")
b28 = tk.Button(root, text="top_side", cursor="top_side")
b29 = tk.Button(root, text="top_left_corner", cursor="top_left_corner")
b30 = tk.Button(root, text="top_right_corner", cursor="top_right_corner")
b1.pack()
b2.pack()
b3.pack()
b4.pack()
b5.pack()
b6.pack()
b7.pack()
b8.pack()
b9.pack()
b10.pack()
b11.pack()
b12.pack()
b13.pack()
b14.pack()
b15.pack()
b16.pack()
b17.pack()
b18.pack()
b19.pack()
b20.pack()
b21.pack()
b22.pack()
b23.pack()
b24.pack()
b25.pack()
b26.pack()
b27.pack()
b28.pack()
b29.pack()
b30.pack()

print("penis")